### ISSUE TITLE
基于gmssl实现国密ssl的进度

### ISSUE THREAD

**Issue by starup** [LiTianjue/CNssl_dev#2]
哥们你好，我也在研究国密ssl通信这块，不知道你现在进度如何？
我把你的代码克隆，编译通过了，我看很多地方都还未实现，不知道是基于gmssl来做快呢？
还是自己按照国密ssl的协议写一套快呢？希望能够多交流一下。

**Comment by LiTianjue** [comment]
感觉做不下去了，目前开发处于停顿状态，是基于openssl来做的，没有重新实现协议，但是openssl的代码总的来说是比较乱的，要是条件允许，看看用其他的实现来完成
